server:
  port: 8082

spring:
  datasource:
    url: ${BARCODE_DB_URL:jdbc:postgresql://localhost:5433/barcodedb}
    username: ${BARCODE_DB_USERNAME:postgres}
    password: ${BARCODE_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      barcode-events: ${BARCODE_EVENTS_TOPIC:barcode-events}