server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${BARCODE_DB_URL}
    username: ${BARCODE_DB_USERNAME}
    password: ${BARCODE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      barcode-events: ${BARCODE_EVENTS_TOPIC:barcode-events}