server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:product-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.migros.casestudy.product.event.BarcodeGeneratedEvent
        spring.json.trusted.packages: com.migros.casestudy.product.event

clients:
  category-service:
    url: ${CATEGORY_SERVICE_URL}
  barcode-service:
    url: ${BARCODE_SERVICE_URL}

app:
  kafka:
    topics:
      barcode-events: ${BARCODE_EVENTS_TOPIC:barcode-events}